# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
sudo: required
julia:
  # - release
  - 0.4
  - nightly
notifications:
  email: false
script:
 # SampledSignals is unregistered so clone it for testing
 - julia -e 'Pkg.clone("https://github.com/JuliaAudio/SampledSignals.jl.git")'
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia -e 'Pkg.clone(pwd()); Pkg.build("PortAudio"); Pkg.test("PortAudio"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("PortAudio")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
