# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
sudo: required
julia:
  # - release
  - 0.4
  - 0.5
notifications:
  email: false
script:
  # we can't actually run on travis, so just make sure it's installable
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia -e 'Pkg.clone(pwd()); Pkg.build("PortAudio"); Pkg.checkout("Compat"); Pkg.checkout("RingBuffers"); Pkg.checkout("SampledSignals"); using PortAudio'
