name = "PortAudio"
uuid = "80ea8bcb-4634-5cb3-8ee8-a132660d1d2d"
repo = "https://github.com/JuliaAudio/PortAudio.jl.git"
version = "2.0.0"

[deps]
alsa_plugins_jll = "5ac2f6bb-493e-5871-9171-112d4c21a6e7"
BitFlags = "d1d4a3ce-64b1-5f1a-9ba4-7e7e69966f35"
libportaudio_jll = "2d7b7beb-0762-5160-978e-1ab83a1e8a31"

[compat]
julia = "1.3"
alsa_plugins_jll = "1.2.2"
BitFlags = "0.1.3"
libportaudio_jll = "19.6.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
